name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  get_it: ^7.6.8
  device_info_plus: ^9.0.3
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  dropdown_button2: ^2.3.9
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  provider: ^6.1.2
  url_launcher: ^6.2.4
  firebase_core: ^2.30.1
  firebase_messaging: ^14.8.0
  flutter_local_notifications: ^16.3.1+1
  image_picker: ^1.0.8
  flutter_google_places: ^0.3.0
  google_api_headers: ^1.6.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.3.1
  google_map_polyline_new: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    
  fonts:
    - family: Expo
      fonts:
        - asset: assets/fonts/Expo/Expo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Expo/Expo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Expo/Expo-Light.ttf
          weight: 300
        - asset: assets/fonts/Expo/Expo-Medium.ttf
          weight: 500
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik/Rubik-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf

